// src/lib/Navbar.svelte
<script>
  let currentLanguage = "java";
  const languages = ["Java", "Javascript", "Typescript", "Python", "Rust"];
</script>

<nav class="navbar">
  <a href="/" class="home"> Home </a>
  <div class="container">
    <div class="languages">
      <img
        class="container-icon"
        src={icons[language.toLowerCase()]}
        alt={icons[language.toLowerCase()]}
      />
    </div>
    <div class="dropdown">
      <ul class="no-dot-ul">
        {#each languages as language}
          <li on:click={() => (currentLanguage = language)}>
            <img class="icon" src={icons[language.toLowerCase()]} />
          </li>
        {/each}
      </ul>
    </div>
  </div>
</nav>

<style>
</style>

// src/components/navbar/NavBar.tsx
import styles from "./navbar.module.css";
import { useState } from "react";
import { icons } from "./icons";

export default function Navbar() {
  const [language, setLanguage] = useState("java");
  const languages = ["Java", "Javascript", "Typescript", "Python", "Rust"];

  return (
    <nav className={styles["navbar"]}>
      <a href={"/"} className={styles["home"]}>
        Home
      </a>
      <div className={styles["container"]}>
        <div className={styles["languages"]}>
          <img
            className={styles["container-icon"]}
            src={icons[language.toLowerCase()]}
          />
        </div>
        <div className={styles["dropdown"]}>
          <ul className={styles["no-dot-ul"]}>
            {languages.map((language: string, i: number) => {
              return (
                <li onClick={() => setLanguage(language)} key={i}>
                  <img
                    className={styles["icon"]}
                    src={icons[language.toLowerCase()]}
                  />
                </li>
              );
            })}
          </ul>
        </div>
      </div>
    </nav>
  );
}
